### ISSUE TITLE
Exposing a port for the node service

### ISSUE THREAD

**Issue by jake-harris** [shipping-docker/vessel#101]
## Description
I'm attempting to expose a port on the `node` service to run [storybook](https://storybook.js.org/).

I added a `ports` key to the `docker-compose.yml`:
```
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    ports:
      - "${STORYBOOK_PORT}:9001"
```
I added a variable to `.env`: 
```
STORYBOOK_PORT=9001
```

I added the bash wrapper for the env variable in `vessel`:
```
export STORYBOOK_PORT=${STORYBOOK_PORT:-9001}
```

Then I run `./vessel yarn storybook`, which is an alias for `start-storybook --ci -p 9001 -c ./resources/js/.storybook`.

This generates the following output
```
➜  my-app git:(react_storybook) ✗ ./vessel yarn storybook
yarn run v1.12.3
$ start-storybook --ci -p 9001 -c ./resources/js/.storybook
info @storybook/react v4.1.11
info 
info => Loading presets
info => Loading presets
info => Using base config because react-scripts is not installed.
info => Using default webpack setup based on "create-react-app".
info => Using base config because react-scripts is not installed.
webpack built 5e118cecc475ef46d285 in 2828ms                                                                            
╭────────────────────────────────────────────────╮
│                                                │
│   Storybook 4.1.11 started                     │
│   3.44 s for manager and 3.16 s for preview    │
│                                                │
│   Local:            http://localhost:9001/     │
│   On your network:  http://172.26.0.2:9001/    │
│                                                │
╰────────────────────────────────────────────────╯
```

So far that all seems normal, but accessing http://localhost:9001 times out.

Finally, here's the `docker ps` output: 
```
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                                NAMES
90d54f8a544f        vessel/node          "yarn storybook"         22 seconds ago       Up 21 seconds                                            my-app_node_run_2217684cc83a
``` 

Notice the frustratingly vacant `PORTS` section. 

I'm sure I'm missing something obvious with docker here, but how can I expose a port from the `node` container?

## OS

My OS is:

[🐧] Linux

## Docker

The output of `docker version`: 

```
➜  ~ docker version
Client:
 Version:           18.09.1-ce
 API version:       1.39
 Go version:        go1.11.4
 Git commit:        4c52b901c6
 Built:             Thu Jan 10 06:51:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       4c52b901c6
  Built:            Thu Jan 10 06:50:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

The output of `docker-compose version`:

```
➜  ~ docker-compose version
docker-compose version 1.23.2, build unknown
docker-py version: 3.7.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018

```

**Comment by fideloper** [comment]
Hi!

I tested this out real quick - In the `vessel` script, Node tasks are all assumed to be one-off commands. So, it uses `docker-compose run`, which [is intended to be for one-off commands and thus does not map ports](https://github.com/docker/compose/issues/1256#issuecomment-90135857).

You should be able to do one of the following:

Edit `vessel` and edit the `yarn` command to expose the port you'd like (`-p $STORYBOOK_PORT:9001`):

```bash
elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm \
            -p $STORYBOOK_PORT:9001
            node \
            yarn "$@"
```


OR

Edit `docker-comose.yml` and copy the `node` service (or edit the `node` service), giving it a command to run on startup, so you can use `./vessel start` or `./vessel up -d` and it will start the new `node` service with that port mapping and command.

```yaml
node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    command: yarn storybook
    volumes:
     - .:/var/www/html
    networks:
     - vessel
    ports:
     - "${STORYBOOK_PORT}:9001"
```

**Comment by jake-harris** [comment]
In hindsight, it makes perfect sense `docker-compose run` doesn't expose the port and I should have dug deeper there. I think I'll just add a storybook service as you suggested. Cheers, and thanks for the quick turnaround on such a big day. Speaking of which, I'm loving [MySQL backups](https://courses.serversforhackers.com/mysql-backups) so far.

**Comment by jake-harris** [comment]
For future googlers, here's what I ended up with:

```
  storybook:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    command: bash -c "yarn && yarn storybook"
    volumes:
     - .:/var/www/html
    networks:
     - vessel
    ports:
     - "${STORYBOOK_PORT}:9001"
```

This will install all yarn dependencies (useful for the first time its run) and start storybook on the port. You'll have to follow the instructions to add environment the variable [here](https://vessel.shippingdocker.com/docs/customizing-vessel/) or see how I did it above.
