### ISSUE TITLE
Connecting to Redis?

### ISSUE THREAD

**Issue by cloudbluedigital** [shipping-docker/vessel#73]
Hello guys, is it possible to expose redis connection so I can connect to it from my host just like we connect to sql?

**Comment by fideloper** [comment]
Certainly!
Update your `docker-compose.yml` file

from:

```yaml
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
```

to:

```yaml
  redis:
    image: redis:alpine
    ports:
      - 6379: 6379
    volumes:
     - vesselredis:/data
    networks:
     - vessel
```

The key part is `ports` where the port on the left side of the `:` is the port on your host machine and can be any port you'd like, and the port on the right side is the port redis is listening on, and must be `6379`.
