### ISSUE TITLE
PostgreSQL Role does not exists

### ISSUE THREAD

**Issue by mardon** [shipping-docker/vessel#89]
## Description
Im trying configure vessel with PostgeSQL, but in the dbeaver when i try connet to PostgreSQL I obtain error the role not exists for role root and homestead

## OS

My OS is: LinuxMint

## Docker

The output of `docker version`: 

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

The output of `docker-compose version`:

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

in .env i have

```
DB_CONNECTION=pgsql
DB_HOST=pgsql
DB_PORT=5432
DB_DATABASE=cart
DB_USERNAME=homestead
DB_PASSWORD=secret

```
in docker-compose.yml

```
  pgsql:
    image: postgres:10.0
    ports:
     - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
     - vesselmysql:/var/lib/postgresql/data
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - vessel

```

in vessel script

```
export APP_PORT=${APP_PORT:-80}
export MYSQL_PORT=${MYSQL_PORT:-3306}
export PGSQL_PORT=${PGSQL_PORT:-5432}
export WWWUSER=${WWWUSER:-$UID}
```
